### ISSUE TITLE
/user/local/bin does not exist on fresh install

### ISSUE THREAD

**Issue by fvumbaca** [azohra/strapped#14]
When installing strapped.sh on a fresh mac, the install will fail because `/usr/local/bin` does not yet exist on the system.

**Proposed Solutions**

1. Create the directory if it doesn't exist. (Permission problems? Alternative dirs?)
2. Don't install strapped.sh and run it via curl directly.

**Comment by fvumbaca** [comment]
I am kind of leaning towards curling it each time. We already curl everything else. This way it does not require any permissions to run at all... not even `chmod`ing the installed script.

**Comment by MatthewNielsen27** [comment]
Personally I am opposed to curling each time as it feels less refined. But if we are going with meme status we could follow through with this and just never have any strapped code on your computer. I also see the benefits of not having to handle permissions at all. But may just be a cop-out as every other installer probably handles these cases.

**Comment by fvumbaca** [comment]
Yea I now agree after talking with @tk8817. I will work on a PR.

**Comment by MatthewNielsen27** [comment]
Thank

**Comment by fvumbaca** [comment]
I quickly wrote out some quick error messages and suggestions in the messages on how to resolve issues when installing. The PR is linked above - take a look to make sure this is what we are all thinking before merging.
