### ISSUE TITLE
Brew.sh strap generates confusing error message

### ISSUE THREAD

**Issue by WF-Home** [azohra/strapped#20]
The error message for the Brew.sh strap is seemingly reverse. I cancelled strapped a few time to check that my packages were being installed.

**To Reproduce**
Packages on the config.yml that is currently not installed on the machine generates an error message, while the packages I already have installed says "installing".

**Expected behavior**
Packages currently not installed to say installing while packages already installed will generate a message saying it is already installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/52927342/61845278-93c14d80-ae70-11e9-9510-3c297d221190.png)
all of those packages were installed previously, while jq was still needed to be installed.

**Comment by fvumbaca** [comment]
@WF-Home created MR #21  for this issue!
